name: ci

on: [ push, pull_request ]

jobs:
  test-ubuntu:
    runs-on: self-hosted
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        docker-image: ["python:3.9", "python:3.10"]
    steps:
    - name: Checkout marl_eval
      uses: actions/checkout@v2
    - name: Check format and types
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/marl_eval" \
            -w "/tmp/marl_eval" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/check_format.sh
    - name: Run tests in docker
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/marl_eval" \
            -w "/tmp/marl_eval" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/tests.sh
